export const specialsText = [
    "You approach a circle of standing stones. Remnants of druidic rituals can be seen. You leave immediately.",
    "You come across a pile of chopped wood. The wood has sat out for a season. You wonder why a woodcutter would have left this here to rot.",
    "You find a lone fountain. “Why would someone build this here?” you think to yourself. You take a sip of the clear, inviting water. You feel changed.",
    "You pass an ancient oak. Something strikes you about this tree. You feel like if you close your eyes you can almost hear it singing a song.",
    "You find a dusty scroll hidden under a rock outcropping. The language is foreign to you. You keep the scroll for kindling.",
    "You see an orb of pulsating light floating across the ground.  “A will-o'-the-wisp!” you exclaim. You run terrified.",
    "A key sits half buried in the dirt. Someone somewhere is missing this key. You take it for the iron.",
    "You find a candle stuck to a rock. This looks to have been part of some ritual. The area gives you an unsettled feeling. You leave quietly.",
    "You see a rainbow. So beautiful.",
    "You see a flower. Its beauty captures you and you stop to smell it. Its fragrance is sweet and satisfying.",
    "You come upon a large toadstool. For a brief moment you were sure you saw a small human figure sitting upon it. Whatever was there is gone now.",
    "You come across a sea shell. You lift it to your ear and hear the ocean. What witchcraft is this!!!!",
    "You see a skull peeking out of the earth. The skull is ancient. You say a prayer and continue on your way.",
    "A glint catches your eye. Upon further inspection you find that it is a clear rock. You huck it at a tree and continue your travels.",
    "The sound of a bell starts gently ringing. It grows closer. You hide. The sound passes close and then fades off into the distance. You saw nothing.",
    "You come upon an old woman who offers to tell you your future. She says you will never satisfy your insatiable hunger for knowledge unless you can find the ship made of iron.",
    "A giant stone head sits out in the open. Scratched in the back is a map that seems to show a city out in the ocean and creatures half human and half fish.",
    "You come across a lemon tree. “Not today scurvy!” you exclaim."
];